logging:
  level:
    org.hibernate.engine.transaction.jta.platform.internal: ERROR

spring:
  profiles: dev
  application:
    name: taskboard
  datasource:
    driver-class-name: org.postgresql.Driver
  flyway:
    enabled: true
    locations: classpath:db/migration
    validate-on-migrate: true
  jpa:
    open-in-view: false

springdoc:
    api-docs:
        path: /api-docs
    swagger-ui:
        path: /swagger-ui.html

---
spring:
  config:
    activate:
      on-profile: dev
  datasource:
    url: jdbc:postgresql://localhost:5432/postgres
    username: postgres
    password: postgres

server:
  port: 8080
  error:
    include-message: always
